ts build on ps desktop

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,261 +1,271 @@
 ﻿name: Build
 on:
-    workflow_dispatch:
-    pull_request:
-        branches:
-            - main
-        paths:
-            - "source/**"
-            - "tests/**"
-    push:
-        branches:
-            - main
-        tags-ignore:
-            - "*-*"
-        paths:
-            - "source/**"
-            - "tests/**"
+  workflow_dispatch:
+  pull_request:
+    branches:
+      - main
+    paths:
+      - "source/**"
+      - "tests/**"
+  push:
+    branches:
+      - main
+    tags-ignore:
+      - "*-*"
+    paths:
+      - "source/**"
+      - "tests/**"
 
 env:
-    PSTOOLS_APITOKEN: ${{ secrets.PSTOOLS_APITOKEN }}
-    PSTOOLS_SOURCE: ${{ secrets.PSTOOLS_SOURCE }}
-    PSIMMICHAPIKEY: ${{ secrets.PSIMMICHAPIKEY }}
-    PSIMMICHPASSWORD: ${{ secrets.PSIMMICHPASSWORD }}
-    PSIMMICHURI: ${{ secrets.PSIMMICHURI }}
-    PSIMMICHUSER: ${{ secrets.PSIMMICHUSER }}
+  PSTOOLS_APITOKEN: ${{ secrets.PSTOOLS_APITOKEN }}
+  PSTOOLS_SOURCE: ${{ secrets.PSTOOLS_SOURCE }}
+  PSIMMICHAPIKEY: ${{ secrets.PSIMMICHAPIKEY }}
+  PSIMMICHPASSWORD: ${{ secrets.PSIMMICHPASSWORD }}
+  PSIMMICHURI: ${{ secrets.PSIMMICHURI }}
+  PSIMMICHUSER: ${{ secrets.PSIMMICHUSER }}
 
 jobs:
-    Build:
-        name: Build
-        runs-on: ubuntu-latest
-        steps:
-            - uses: actions/checkout@v4
-              with:
-                  fetch-depth: "0"
-            - name: Calculate ModuleVersion (GitVersion)
-              run: |
-                  dotnet tool install --global GitVersion.Tool --version 5.*
-                  dotnet-gitversion
-                  $gitVersionObject = dotnet-gitversion | ConvertFrom-Json
-                  $gitVersionObject.PSObject.Properties.ForEach{
-                      Write-Host -Object "Setting Task Variable '$($_.Name)' with value '$($_.Value)'."
-                      Write-Output "$($_.Name)=$($_.Value)" >> $env:GITHUB_ENV
-                  }
-                  Write-Output "updatebuildnumber=$($gitVersionObject.FullSemVer)" >> $env:GITHUB_ENV
-              shell: pwsh
-            - name: Build & Package Module
-              run: |
-                  ./build.ps1 -ResolveDependency -tasks pack
-              shell: pwsh
-            - uses: actions/upload-artifact@v4
-              with:
-                  name: output
-                  path: output
-    Test_Linux_Core:
-        name: Test Unit - Linux
-        runs-on: ubuntu-latest
-        needs: Build
-        steps:
-            - uses: actions/checkout@v4
-              with:
-                  fetch-depth: "0"
-            - uses: actions/download-artifact@v4
-              with:
-                  name: output
-                  path: "output"
-            - name: Linux_Core
-              run: |
-                  ./build.ps1 -ResolveDependency -tasks test -pesterpath "$((Get-Location).Path)\tests\Unit"
-              shell: pwsh
-            - uses: actions/upload-artifact@v4
-              with:
-                  name: CodeCoverage_Linux_Core
-                  path: output/testResults/
-    Test_Windows_Core:
-        name: Test Unit - Win Core
-        runs-on: windows-latest
-        needs: Build
-        steps:
-            - uses: actions/checkout@v4
-              with:
-                  fetch-depth: "0"
-            - uses: actions/download-artifact@v4
-              with:
-                  name: output
-                  path: "output"
-            - name: Windows_Core
-              run: |
-                  ./build.ps1 -ResolveDependency -tasks test -pesterpath "$((Get-Location).Path)\tests\Unit"
-              shell: pwsh
-            - uses: actions/upload-artifact@v4
-              with:
-                  name: CodeCoverage_Windows_Core
-                  path: output/testResults/
-    Test_Windows_Desktop:
-        name: Test Unit - Win Desktop
-        runs-on: windows-latest
-        needs: Build
-        steps:
-            - uses: actions/checkout@v4
-              with:
-                  fetch-depth: "0"
-            - uses: actions/download-artifact@v4
-              with:
-                  name: output
-                  path: "output"
-            - name: Windows_Desktop
-              run: |
-                  ./build.ps1 -ResolveDependency -tasks test -pesterpath "$((Get-Location).Path)\tests\Unit"
-              shell: powershell
-            - uses: actions/upload-artifact@v4
-              with:
-                  name: CodeCoverage_Windows_Desktop
-                  path: output/testResults/
-    Test_MacOS_Core:
-        name: Test Unit - MacOS
-        runs-on: macos-latest
-        needs: Build
-        steps:
-            - uses: actions/checkout@v4
-              with:
-                  fetch-depth: "0"
-            - uses: actions/download-artifact@v4
-              with:
-                  name: output
-                  path: "output"
-            - name: MacOS_Core
-              run: |
-                  ./build.ps1 -ResolveDependency -tasks test -pesterpath "$((Get-Location).Path)\tests\Unit"
-              shell: pwsh
-            - uses: actions/upload-artifact@v4
-              with:
-                  name: CodeCoverage_MacOS_Core
-                  path: output/testResults/
-    Test_Integration:
-        name: Test Integration
-        runs-on: ubuntu-latest
-        needs: Build
-        steps:
-            - uses: actions/checkout@v4
-              with:
-                  fetch-depth: "0"
-            - uses: actions/download-artifact@v4
-              with:
-                  name: output
-                  path: "output"
-            - name: Pester
-              run: |
-                  ./build.ps1 -ResolveDependency -tasks test -pesterpath "$((Get-Location).Path)\tests\Integration"
-              shell: pwsh
-            - uses: actions/upload-artifact@v4
-              with:
-                  name: CodeCoverage_Integration
-                  path: output/testResults/
-    Test_Quality:
-        name: Test Quality
-        runs-on: ubuntu-latest
-        needs: Build
-        steps:
-            - uses: actions/checkout@v4
-              with:
-                  fetch-depth: "0"
-            - uses: actions/download-artifact@v4
-              with:
-                  name: output
-                  path: "output"
-            - name: Pester
-              run: |
-                  ./build.ps1 -ResolveDependency -tasks test -pesterpath "$((Get-Location).Path)\tests\QA" -CodeCoverageThreshold 0
-              shell: pwsh
-    Publish_Code_Coverage:
-        name: Code Coverage
-        runs-on: ubuntu-latest
-        needs:
-            - Test_MacOS_Core
-            - Test_Windows_Desktop
-            - Test_Windows_Core
-            - Test_Linux_Core
-            - Test_Integration
-        steps:
-            - uses: actions/checkout@v4
-              with:
-                  fetch-depth: "0"
-            - uses: actions/download-artifact@v4
-              with:
-                  name: output
-                  path: "output"
-            - uses: actions/download-artifact@v4
-              with:
-                  name: CodeCoverage_Linux_Core
-                  path: output/testResults/CodeCoverage_Linux_Core
-            - uses: actions/download-artifact@v4
-              with:
-                  name: CodeCoverage_MacOS_Core
-                  path: output/testResults/CodeCoverage_MacOS_Core
-            - uses: actions/download-artifact@v4
-              with:
-                  name: CodeCoverage_Windows_Core
-                  path: output/testResults/CodeCoverage_Windows_Core
-            - uses: actions/download-artifact@v4
-              with:
-                  name: CodeCoverage_Windows_Desktop
-                  path: output/testResults/CodeCoverage_Windows_Desktop
-            - uses: actions/download-artifact@v4
-              with:
-                  name: CodeCoverage_Integration
-                  path: output/testResults/CodeCoverage_Integration
-            - name: Merge Code Coverage files
-              run: |
-                  ./build.ps1 -ResolveDependency -tasks merge
-              shell: pwsh
-            - name: Codecov
-              uses: codecov/codecov-action@v3
-              with:
-                  name: civoShell
-                  token: ${{ secrets.CODECOV_TOKEN }}
-                  #file: ./output/testResults/CodeCov.xml
-                  file: ./output/testResults/JaCoCo_coverage.xml
-            - uses: actions/upload-artifact@v4
-              with:
-                  name: CodeCovState
-                  path: ./
+  Build:
+    name: Build
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: "0"
+      - name: Calculate ModuleVersion (GitVersion)
+        run: |
+          dotnet tool install --global GitVersion.Tool --version 5.*
+          dotnet-gitversion
+          $gitVersionObject = dotnet-gitversion | ConvertFrom-Json
+          $gitVersionObject.PSObject.Properties.ForEach{
+              Write-Host -Object "Setting Task Variable '$($_.Name)' with value '$($_.Value)'."
+              Write-Output "$($_.Name)=$($_.Value)" >> $env:GITHUB_ENV
+          }
+          Write-Output "updatebuildnumber=$($gitVersionObject.FullSemVer)" >> $env:GITHUB_ENV
+        shell: pwsh
+      - name: Build & Package Module
+        run: |
+          ./build.ps1 -ResolveDependency -tasks pack
+        shell: pwsh
+      - uses: actions/upload-artifact@v4
+        with:
+          name: output
+          path: output
+  Test_Linux_Core:
+    name: Test Unit - Linux
+    runs-on: ubuntu-latest
+    needs: Build
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: "0"
+      - uses: actions/download-artifact@v4
+        with:
+          name: output
+          path: "output"
+      - name: Linux_Core
+        run: |
+          ./build.ps1 -ResolveDependency -tasks test -pesterpath "$((Get-Location).Path)\tests\Unit"
+        shell: pwsh
+      - uses: actions/upload-artifact@v4
+        with:
+          name: CodeCoverage_Linux_Core
+          path: output/testResults/
+  Test_Windows_Core:
+    name: Test Unit - Win Core
+    runs-on: windows-latest
+    needs: Build
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: "0"
+      - uses: actions/download-artifact@v4
+        with:
+          name: output
+          path: "output"
+      - name: Windows_Core
+        run: |
+          ./build.ps1 -ResolveDependency -tasks test -pesterpath "$((Get-Location).Path)\tests\Unit"
+        shell: pwsh
+      - uses: actions/upload-artifact@v4
+        with:
+          name: CodeCoverage_Windows_Core
+          path: output/testResults/
+  Test_Windows_Desktop:
+    name: Test Unit - Win Desktop
+    runs-on: windows-latest
+    needs: Build
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: "0"
+      - uses: actions/download-artifact@v4
+        with:
+          name: output
+          path: "output"
+      - name: Check ModuleBuilder Import
+        run: |
+          try {
+            Import-Module ModuleBuilder -ErrorAction Stop
+            Write-Host "ModuleBuilder imported successfully."
+          } catch {
+            Write-Error "Failed to import ModuleBuilder: $_"
+            exit 1
+          }
+        shell: pwsh
+      - name: Windows_Desktop
+        run: |
+          ./build.ps1 -ResolveDependency -tasks test -pesterpath "$((Get-Location).Path)\tests\Unit"
+        shell: powershell
+      - uses: actions/upload-artifact@v4
+        with:
+          name: CodeCoverage_Windows_Desktop
+          path: output/testResults/
+  Test_MacOS_Core:
+    name: Test Unit - MacOS
+    runs-on: macos-latest
+    needs: Build
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: "0"
+      - uses: actions/download-artifact@v4
+        with:
+          name: output
+          path: "output"
+      - name: MacOS_Core
+        run: |
+          ./build.ps1 -ResolveDependency -tasks test -pesterpath "$((Get-Location).Path)\tests\Unit"
+        shell: pwsh
+      - uses: actions/upload-artifact@v4
+        with:
+          name: CodeCoverage_MacOS_Core
+          path: output/testResults/
+  Test_Integration:
+    name: Test Integration
+    runs-on: ubuntu-latest
+    needs: Build
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: "0"
+      - uses: actions/download-artifact@v4
+        with:
+          name: output
+          path: "output"
+      - name: Pester
+        run: |
+          ./build.ps1 -ResolveDependency -tasks test -pesterpath "$((Get-Location).Path)\tests\Integration"
+        shell: pwsh
+      - uses: actions/upload-artifact@v4
+        with:
+          name: CodeCoverage_Integration
+          path: output/testResults/
+  Test_Quality:
+    name: Test Quality
+    runs-on: ubuntu-latest
+    needs: Build
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: "0"
+      - uses: actions/download-artifact@v4
+        with:
+          name: output
+          path: "output"
+      - name: Pester
+        run: |
+          ./build.ps1 -ResolveDependency -tasks test -pesterpath "$((Get-Location).Path)\tests\QA" -CodeCoverageThreshold 0
+        shell: pwsh
+  Publish_Code_Coverage:
+    name: Code Coverage
+    runs-on: ubuntu-latest
+    needs:
+      - Test_MacOS_Core
+      - Test_Windows_Desktop
+      - Test_Windows_Core
+      - Test_Linux_Core
+      - Test_Integration
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: "0"
+      - uses: actions/download-artifact@v4
+        with:
+          name: output
+          path: "output"
+      - uses: actions/download-artifact@v4
+        with:
+          name: CodeCoverage_Linux_Core
+          path: output/testResults/CodeCoverage_Linux_Core
+      - uses: actions/download-artifact@v4
+        with:
+          name: CodeCoverage_MacOS_Core
+          path: output/testResults/CodeCoverage_MacOS_Core
+      - uses: actions/download-artifact@v4
+        with:
+          name: CodeCoverage_Windows_Core
+          path: output/testResults/CodeCoverage_Windows_Core
+      - uses: actions/download-artifact@v4
+        with:
+          name: CodeCoverage_Windows_Desktop
+          path: output/testResults/CodeCoverage_Windows_Desktop
+      - uses: actions/download-artifact@v4
+        with:
+          name: CodeCoverage_Integration
+          path: output/testResults/CodeCoverage_Integration
+      - name: Merge Code Coverage files
+        run: |
+          ./build.ps1 -ResolveDependency -tasks merge
+        shell: pwsh
+      - name: Codecov
+        uses: codecov/codecov-action@v3
+        with:
+          name: civoShell
+          token: ${{ secrets.CODECOV_TOKEN }}
+          #file: ./output/testResults/CodeCov.xml
+          file: ./output/testResults/JaCoCo_coverage.xml
+      - uses: actions/upload-artifact@v4
+        with:
+          name: CodeCovState
+          path: ./
 
-    Deploy:
-        name: Deploy
-        runs-on: ubuntu-latest
-        needs:
-            - Test_MacOS_Core
-            - Test_Linux_Core
-            - Test_Windows_Core
-            - Test_Windows_Desktop
-            - Test_Integration
-            - Test_Quality
-        if: ${{ success() && (github.ref == 'refs/heads/main' || StartsWith(github.ref,'refs/tags/')) }}
-        steps:
-            - uses: actions/checkout@v4
-              with:
-                  fetch-depth: "0"
-            - uses: actions/download-artifact@v4
-              with:
-                  name: output
-                  path: "output"
-            - run: |
-                  ./build.ps1 -ResolveDependency -tasks publish
-              shell: pwsh
-              env:
-                  GitHubToken: ${{ secrets.GITHUBTOKEN }}
-                  GalleryApiToken: ${{ secrets.GALLERYAPITOKEN }}
-    Cleanup:
-        name: Cleanup
-        runs-on: ubuntu-latest
-        if: ${{ always() }}
-        needs:
-            - Deploy
-            - Publish_Code_Coverage
-        steps:
-            - uses: geekyeggo/delete-artifact@v2
-              with:
-                  name: |
-                      CodeCov*
-                      output
-                  failOnError: false
+  Deploy:
+    name: Deploy
+    runs-on: ubuntu-latest
+    needs:
+      - Test_MacOS_Core
+      - Test_Linux_Core
+      - Test_Windows_Core
+      - Test_Windows_Desktop
+      - Test_Integration
+      - Test_Quality
+    if: ${{ success() && (github.ref == 'refs/heads/main' || StartsWith(github.ref,'refs/tags/')) }}
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: "0"
+      - uses: actions/download-artifact@v4
+        with:
+          name: output
+          path: "output"
+      - run: |
+          ./build.ps1 -ResolveDependency -tasks publish
+        shell: pwsh
+        env:
+          GitHubToken: ${{ secrets.GITHUBTOKEN }}
+          GalleryApiToken: ${{ secrets.GALLERYAPITOKEN }}
+  Cleanup:
+    name: Cleanup
+    runs-on: ubuntu-latest
+    if: ${{ always() }}
+    needs:
+      - Deploy
+      - Publish_Code_Coverage
+    steps:
+      - uses: geekyeggo/delete-artifact@v2
+        with:
+          name: |
+            CodeCov*
+            output
+          failOnError: false
